name: devcontainer

on:
  push:
    branches:
      - main
    paths:
      - .devcontainer/Dockerfile
      - .github/workflows/devcontainer.yml

jobs:
  build_devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .devcontainer/
          file: .devcontainer/Dockerfile
          push: true
          tags: ghcr.io/code-tanks/code-tanks-dart-devcontainer:latest
          cache-from: type=registry,ref=ghcr.io/code-tanks/code-tanks-dart-devcontainer:buildcache
          cache-to: type=registry,ref=ghcr.io/code-tanks/code-tanks-dart-devcontainer:buildcache,mode=max